load("E:/kamagyana/Computing/DARET/R-code-submissions/Asst10.1.RData")
library(Hmisc)
library(sqldf)
library(dplyr)
head(daypolu)
str(daypolu)
length(daypolu)
nrows(daypolu)
nrow(daypolu)
colnames(compdata)
rescoday <- aov(CO~Day,data=compdata)
rescoday
summary(rescoday)
TukeyHSD(rescoday)
table(compdata$CO)
compdata> mutate(compdata, COLEVEL = ifelse(CO=<3,"LOW",ifelse(CO>3&CO=<6,"MODERATE",ifelse(CO>6&CO=<9,"HIGH",ifelse(CO>9,"ALARM","NA")))))
compdata <- mutate(compdata, COLEVEL = ifelse(CO=<3,"LOW",ifelse(CO>3&CO=<6,"MODERATE",ifelse(CO>6&CO=<9,"HIGH",ifelse(CO>9,"ALARM","NA")))))
compdata <- mutate(compdata, COLEVEL = ifelse(CO <= 3,"LOW",ifelse(CO >3 & CO <= 6,"MODERATE",ifelse(CO > 6 & CO =< 9,"HIGH",ifelse(CO > 9,"ALARM","NA")))))
compdata <- mutate(compdata, COLEVEL = ifelse(CO <= 3,"LOW",ifelse(CO >3 & CO <= 6,"MODERATE",ifelse(CO > 6 & CO <= 9,"HIGH",ifelse(CO > 9,"ALARM","NA")))))
table(compdata$COLEVEL)
with(compdata, tapply(CO, list(day,COLEVEL), FUN= count))
with(compdata, tapply(CO, list(Day,COLEVEL), FUN= count))
savehistory("E:/kamagyana/Computing/DARET/R-code-submissions/Asst10.1.RData")
load("E:/kamagyana/Computing/DARET/R-code-submissions/Asst10.1.RData")
load("E:/kamagyana/Computing/DARET/R-code-submissions/Asst10.1.RData")
load("E:/kamagyana/Computing/DARET/R-code-submissions/Asst10.1.RData")
> library(readxl)
library(readxl)
AirQualityUCI <- read_excel("E:/kamagyana/Computing/DARET/Assignments/AirQualityUCI.xlsx")
head(AirQualityUCI)
str(AirQualityUCI)
summary(AirQualityUCI)
nrow(AirQualityUCI)
ncol(AirQualityUCI)
nrow(AirQualityUCI) * ncol(AirQualityUCI)
sum(is.na(AirQualityUCI))
sum(!is.na(AirQualityUCI))
library(naniar)
AQUCI <- AirQualityUCI %>% replace_with_na_all(~.x == -200)
sum(is.na(AQUCI))
sum(!is.na(AQUCI))
sum(is.na(AQUCI)) + sum(!is.na(AQUCI))
summary(AQUCI)
library(pastecs)
stat.desc(AQUCI)
naper <- function(x) {sum(is.na(x)/length(x)*100)}
apply(AQUCI,2,naper)
apply(AQUCI,1,naper)
library(VIM)
missdataplot <- aggr(AQUCI, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, labels=names(data), cex.axis=.7, gap=3, ylab=c("Histogram of missing data","Pattern"))
md.pattern(AQUCI)
colnames(AQUCI)
colnames(AQUCI)[c(3,4,5,6,7,8,9,10,11,12)] <- c("CO","TINO","NMHC","C6H6","TITAN","NOX", "TUNGOX1","NO2","TUNGOX2","INDOX")
colnames(AQUCI)
library(mice)
tempdata <- mice(AQUCI,m=5,maxit=50,meth='pmm',seed=500)
compdata <- complete(tempdata,1)
nrow(compdata)
ncol(compdata)
sum(is.na(compdata))
compdata <- cbind(compdata,AQUCI$Date,AQUCI$Time)
ncol(compdata)
sum(is.na(compdata))
library(dplyr)
colnames(AQUCI)[-c(1,2)]
NUMAQUCI <- AQUCI %>% select(colnames(AQUCI)[-c(1,2)])
str(NUMAQUCI)
NUMAQUCI <- as.data.frame(NUMAQUCI)
tempdata <- mice(NUMAQUCI,m=5,maxit=50,meth='pmm',seed=500)
compdata <- complete(tempdata,1)
nrow(compdata)
ncol(compdata)
sum(is.na(compdata))
compdata <- cbind(compdata,AQUCI$Date,AQUCI$Time)
ncol(compdata)
sum(is.na(compdata))
colnames(compdata)
colnames(compdata)[14] <- "Date"
colnames(compdata)[15] <- "Time"
library(lattice)
library(ggplot2)
xyplot(tempdata,CO~TINO+NMHC,pch=18,cex=1)
numdata <- complete(tempdata,1)
library(stats)
library(car)
library(Hmisc)
rcorr(numdata)
str(numdata)
rcorr(as.matrix(numdata))
install.packages("lubridate")
library(lubridate)
head(compdata$Time)
head(compdata$Date)
timepolu <- aggregate(cbind(CO,TINO,NMHC,C6H6,TITAN,NOX,TUNGOX1,NO2,TUNGOX2,INDOX)~hour(Time),data=compdata,mean)
timepolu <- as.data.frame(timepolu)
pairs(~CO+NMHC+C6H6+NOX+NO2, data = timepolu)
library(dplyr)
timepolu$total <- rowSums(timepolu)
head(timepolu)
max(timepolu$total)
timepolu$total
plot(timepolu$`hour(Time)`,timepolu$total)
plot(timepolu$`hour(Time)`,timepolu$total, type = 'h')
timepolu <- mutate(timepolu,trupol = CO+NMHC+C6H6+NOX+NO2)
plot(timepolu$trupol)
max(timepolu$trupol)
plot(timepolu$'hour(Time)',timepolu$trupol, type= 'h')
pairs(~CO+NMHC+C6H6+NOX+NO2, data = timepolu)
library(dplyr)
polnumdata <- numdata %>% select("CO",'NMHC',"C6H6","NOX","NO2","T","RH","AH")
library(Hmisc)
rcorr(as.matrix(polnumdata))
compdata$Day <- weekdays(compdata$Date)
head(compdata$Day)
table(compdata$Day)
compdata$Month <- month(compdata$Date)
library(lubridate)
compdata$Month <- month(ymd(compdata$Date))
table(compdata$Month)
library(ggplot2)
qplot(Day, CO, data = compdata,
geom= "boxplot", fill = Day)
daypolu <- aggregate(cbind(CO,NMHC,C6H6,NOX,NO2)~weekdays(Date),data=compdata,mean)
timepolu1 <- aggregate(cbind(CO,NMHC,C6H6,NOX,NO2)~hour(Time),data=compdata,mean)
compdata$Hour <- hour(compdata$Time)
qplot(Day, CO, data = compdata, geom= "boxplot", fill = Day)
qplot(Hour, CO, data = compdata, geom= "boxplot", fill = Hour)
ggplot(compdata,aes(factor(Hour),CO,fill=factor(Hour))) + geom_boxplot()
polnumdata <- compdata %>% select("CO","NMHC","C6H6","NOX","NO2","T","RH","AH","Date","Time","Day","Hour")
Day = polnumdata %>% select("CO","NMHC","C6H6","NOX","NO2","Day") %>% melt(id.var="Day")
ggplot(Day,aes(variable,value))+geom_boxplot(aes(fill=Day))+facet_wrap(~variable,scales='free')
Hour = polnumdata %>% select("CO","NMHC","C6H6","NOX","NO2","Hour") %>% melt(id.var="Hour")
ggplot(Hour,aes(variable,value))+geom_boxplot(aes(fill=factor(Hour)))+facet_wrap(~variable,scales='free')
cores <- aov(CO ~ Day, data = polnumdata)
summary(cores)
library(stats)
TukeyHSD(cores)
nmhcres <- aov(NMHC ~ Day, data = polnumdata)
summary(nmhcres)
c6h6res <- aov(C6H6 ~ Day, data = polnumdata)
summary(c6h6res)
noxres <- aov(NOX ~ Day, data = polnumdata)
summary(noxres)
no2res <- aov(NO2 ~ Day, data = polnumdata)
summary(no2res)
cores1 <- aov(CO ~ Hour, data = polnumdata)
summary(cores1)
TukeyHSD(cores1)
polnumdata$segment <- with(polnumdata,ifelse(Hour >=0 & Hour <4,"MIDNIGHT",ifelse(Hour >=4 & Hour <7,"ELYMORN",ifelse(Hour >=7 & Hour <12, "MORN",ifelse(Hour == 12, "NOON",ifelse(Hour >12 & Hour <16, "AFNOON",ifelse(Hour>=16 & Hour <19,"EVEN",ifelse(Hour >=19 & Hour <=23,"NITE","NA"))))))))
table(polnumdata$segment)
colnames(compdata)
rescoday <- aov(CO~Day,data=compdata)
summary(rescoday)
TukeyHSD(rescoday)
colnames(compdata)
table(compdata$CO)
compdata <- mutate(compdata, COLEVEL = ifelse(CO <= 3,"LOW",ifelse(CO >3 & CO <= 6,"MODERATE",ifelse(CO > 6 & CO <= 9,"HIGH",ifelse(CO > 9,"ALARM","NA")))))
table(compdata$COLEVEL)
head(compdata$COLEVEL)
with(compdata, tapply(CO, list(day,COLEVEL),FUN=Mean))
table(compdata$Day, compdata$COLEVEL)
table(compdata$Time, compdata$COLEVEL)
table(compdata$Hour, compdata$COLEVEL)
savehistory("E:/kamagyana/Computing/DARET/R-code-submissions/Asst10.1")
savehistory("E:/kamagyana/Computing/DARET/R-code-submissions/Asst10.1.r")
